# Word predictor

# -*- coding: utf-8 -*-
"""Next Word Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eFy3Mb2EjuFa8EvINjLQa-3n5kmXU82f
"""

from datasets import load_dataset

ds = load_dataset("Sakonii/nepalitext-language-model-dataset")
ds

print(ds)

# check available splits
print(ds.keys())

# take a sample
sample = ds["train"][0]
print(sample)

# check columns
print(ds["train"].column_names)

train_ds = ds["train"]
test_ds = ds["test"]

print("Train size:", len(train_ds))
print("Test size:", len(test_ds))

# preview few samples
for i in range(5):
    print(train_ds[i]["text"])

import re

train_ds = ds["train"]
test_ds = ds["test"]

def clean_text(text: str) -> str:
    if text is None:
        return ""

    text = text.replace("\ufeff", " ")
    text = text.replace("\xa0", " ")
    text = text.replace("\r", "\n")
    text = text.replace("\t", " ")

    # remove zero-width / invisible chars
    text = re.sub(r"[\u200b-\u200f\u202a-\u202e]", "", text)

    # normalize repeated spaces
    text = re.sub(r"[ ]{2,}", " ", text)

    # normalize repeated newlines
    text = re.sub(r"\n{2,}", "\n", text)

    # normalize repeated danda
    text = text.replace("।।", "।")

    return text.strip()

# preview cleaned samples
for i in range(5):
    raw = train_ds[i]["text"]
    cleaned = clean_text(raw)
    print("RAW   :", repr(raw))
    print("CLEAN :", repr(cleaned))
    print("-" * 80)

def is_good_text(text: str) -> bool:
    text = clean_text(text)

    if not text:
        return False

    # too short
    if len(text) < 5:
        return False

    # remove obvious junk
    bad_patterns = [
        r"http[s]?://",
        r"www\.",
        r"<[^>]+>",
    ]
    for pat in bad_patterns:
        if re.search(pat, text):
            return False

    # require enough Devanagari characters
    dev_chars = re.findall(r"[\u0900-\u097F]", text)
    if len(dev_chars) < 3:
        return False

    return True

# preview filter behavior
for i in range(10):
    t = train_ds[i]["text"]
    print(i, is_good_text(t), repr(clean_text(t)))

MAX_TRAIN_SAMPLES = 500000
MAX_TEST_SAMPLES = 50000

train_subset = train_ds.select(range(min(MAX_TRAIN_SAMPLES, len(train_ds))))
test_subset = test_ds.select(range(min(MAX_TEST_SAMPLES, len(test_ds))))

print("Train subset:", len(train_subset))
print("Test subset:", len(test_subset))

train_texts = []
for item in train_subset:
    text = clean_text(item["text"])
    if is_good_text(text):
        train_texts.append(text)

test_texts = []
for item in test_subset:
    text = clean_text(item["text"])
    if is_good_text(text):
        test_texts.append(text)

print("Filtered train texts:", len(train_texts))
print("Filtered test texts:", len(test_texts))

print("\nSample train texts:")
for i in range(5):
    print(train_texts[i])

def word_len_stats(texts):
    lengths = [len(t.split()) for t in texts if t.strip()]
    lengths_sorted = sorted(lengths)

    def percentile(p):
        idx = int(len(lengths_sorted) * p / 100)
        idx = min(idx, len(lengths_sorted) - 1)
        return lengths_sorted[idx]

    print("Count:", len(lengths))
    print("Min words:", min(lengths))
    print("Max words:", max(lengths))
    print("Avg words:", sum(lengths) / len(lengths))
    print("P50:", percentile(50))
    print("P75:", percentile(75))
    print("P90:", percentile(90))
    print("P95:", percentile(95))
    print("P99:", percentile(99))

print("Train stats:")
word_len_stats(train_texts)

print("\nTest stats:")
word_len_stats(test_texts)

MIN_WORDS = 3
MAX_WORDS = 80   # based on P95

def filter_by_length(texts):
    filtered = []
    for t in texts:
        n = len(t.split())
        if MIN_WORDS <= n <= MAX_WORDS:
            filtered.append(t)
    return filtered

train_texts = filter_by_length(train_texts)
test_texts = filter_by_length(test_texts)

print("After length filtering:")
print("Train:", len(train_texts))
print("Test :", len(test_texts))

print("\nSample:")
for i in range(5):
    print(train_texts[i])

train_texts = list(dict.fromkeys(train_texts))
test_texts = list(dict.fromkeys(test_texts))

print("After deduplication:")
print("Train:", len(train_texts))
print("Test :", len(test_texts))

print("\nSample:")
for i in range(5):
    print(train_texts[i])

from google.colab import drive
drive.mount('/content/drive')

TRAIN_FILE = "/content/train.txt"
TEST_FILE = "/content/test.txt"

with open(TRAIN_FILE, "w", encoding="utf-8") as f:
    for t in train_texts:
        f.write(t.strip() + "\n")

with open(TEST_FILE, "w", encoding="utf-8") as f:
    for t in test_texts:
        f.write(t.strip() + "\n")

print("Saved:")
print(TRAIN_FILE)
print(TEST_FILE)

!pip -q install sentencepiece

import sentencepiece as spm

VOCAB_SIZE = 8000
MODEL_PREFIX = "/content/nepali_sp"

spm.SentencePieceTrainer.train(
    input=TRAIN_FILE,
    model_prefix=MODEL_PREFIX,
    vocab_size=VOCAB_SIZE,
    model_type="unigram",
    character_coverage=1.0,
    unk_id=0,
    pad_id=1,
    bos_id=2,
    eos_id=3,
    split_digits=False,
    normalization_rule_name="identity",
)

sp = spm.SentencePieceProcessor()
sp.load(f"{MODEL_PREFIX}.model")

# test sentences
samples = [
    "नेपाल एक सुन्दर देश हो।",
    "काठमाडौं नेपालको राजधानी हो।",
    "विद्यार्थीहरू विद्यालयमा अध्ययन गरिरहेका छन्।"
]

for s in samples:
    pieces = sp.encode(s, out_type=str)
    ids = sp.encode(s, out_type=int)

    print("TEXT :", s)
    print("TOKENS:", pieces)
    print("IDS   :", ids)
    print("DECODE:", sp.decode(ids))
    print("-" * 80)

MAX_LEN = 48   # keep small for fast training

def encode_texts(texts, sp, max_len):
    encoded = []

    for t in texts:
        ids = sp.encode(t, out_type=int)

        # add BOS and EOS
        ids = [sp.bos_id()] + ids + [sp.eos_id()]

        # truncate
        ids = ids[:max_len]

        # pad
        if len(ids) < max_len:
            ids = ids + [sp.pad_id()] * (max_len - len(ids))

        encoded.append(ids)

    return encoded

train_ids = encode_texts(train_texts, sp, MAX_LEN)
test_ids = encode_texts(test_texts, sp, MAX_LEN)

print("Train encoded:", len(train_ids))
print("Sample:", train_ids[0])

import torch
from torch.utils.data import Dataset, DataLoader

class LMDataset(Dataset):
    def __init__(self, sequences):
        self.sequences = sequences

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        x = torch.tensor(self.sequences[idx][:-1], dtype=torch.long)  # input
        y = torch.tensor(self.sequences[idx][1:], dtype=torch.long)   # target
        return x, y

BATCH_SIZE = 64

train_dataset = LMDataset(train_ids)
test_dataset = LMDataset(test_ids)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

# quick check
x, y = next(iter(train_loader))
print("Input shape :", x.shape)
print("Target shape:", y.shape)
print("Sample input :", x[0][:20])
print("Sample target:", y[0][:20])

import math
import torch
import torch.nn as nn

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
VOCAB_SIZE = sp.get_piece_size()

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=512):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float32).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))

        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)

        pe = pe.unsqueeze(0)  # [1, max_len, d_model]
        self.register_buffer("pe", pe)

    def forward(self, x):
        seq_len = x.size(1)
        return x + self.pe[:, :seq_len, :]

class NepaliGPT(nn.Module):
    def __init__(
        self,
        vocab_size,
        d_model=256,
        nhead=4,
        num_layers=4,
        dim_feedforward=1024,
        dropout=0.1,
        max_len=128,
        pad_id=1,
    ):
        super().__init__()
        self.pad_id = pad_id
        self.token_emb = nn.Embedding(vocab_size, d_model, padding_idx=pad_id)
        self.pos_enc = PositionalEncoding(d_model, max_len=max_len)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=dim_feedforward,
            dropout=dropout,
            batch_first=True,
            activation="gelu",
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.lm_head = nn.Linear(d_model, vocab_size)

    def causal_mask(self, seq_len, device):
        mask = torch.triu(torch.ones(seq_len, seq_len, device=device), diagonal=1).bool()
        return mask

    def forward(self, x):
        # x: [B, T]
        padding_mask = (x == self.pad_id)  # [B, T]
        seq_len = x.size(1)
        causal_mask = self.causal_mask(seq_len, x.device)  # [T, T]

        h = self.token_emb(x)                # [B, T, D]
        h = self.pos_enc(h)                  # [B, T, D]
        h = self.transformer(
            h,
            mask=causal_mask,
            src_key_padding_mask=padding_mask
        )                                    # [B, T, D]
        logits = self.lm_head(h)             # [B, T, V]
        return logits

model = NepaliGPT(
    vocab_size=VOCAB_SIZE,
    d_model=256,
    nhead=4,
    num_layers=4,
    dim_feedforward=1024,
    dropout=0.1,
    max_len=MAX_LEN,
    pad_id=sp.pad_id(),
).to(DEVICE)

print(model)
print("Device:", DEVICE)

import torch
import torch.nn as nn
from tqdm.auto import tqdm

EPOCHS = 3
LR = 3e-4

criterion = nn.CrossEntropyLoss(ignore_index=sp.pad_id())
optimizer = torch.optim.AdamW(model.parameters(), lr=LR)

def run_epoch(model, loader, optimizer=None):
    is_train = optimizer is not None
    model.train() if is_train else model.eval()

    total_loss = 0.0
    total_tokens = 0

    pbar = tqdm(loader, desc="train" if is_train else "eval")

    for x, y in pbar:
        x = x.to(DEVICE)
        y = y.to(DEVICE)

        with torch.set_grad_enabled(is_train):
            logits = model(x)   # [B, T, V]

            loss = criterion(
                logits.reshape(-1, logits.size(-1)),
                y.reshape(-1)
            )

            if is_train:
                optimizer.zero_grad()
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()

        non_pad = (y != sp.pad_id()).sum().item()
        total_loss += loss.item() * non_pad
        total_tokens += non_pad

        avg_loss = total_loss / max(total_tokens, 1)
        pbar.set_postfix(loss=avg_loss)

    return total_loss / max(total_tokens, 1)

for epoch in range(1, EPOCHS + 1):
    train_loss = run_epoch(model, train_loader, optimizer)
    val_loss = run_epoch(model, test_loader, optimizer=None)

    print(f"Epoch {epoch}:")
    print(f"  Train Loss: {train_loss:.4f}")
    print(f"  Val Loss  : {val_loss:.4f}")
    print("-" * 50)

    # Save checkpoint after each epoch
    torch.save({
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'train_loss': train_loss,
        'val_loss': val_loss,
    }, f"/content/drive/MyDrive/Model/nepali_gpt_epoch_{epoch}.pt")
    print(f"Saved checkpoint: /content/drive/MyDrive/Model/nepali_gpt_epoch_{epoch}.pt")

import torch
import torch.nn.functional as F

# load best / latest checkpoint
CHECKPOINT_PATH = "/content/drive/MyDrive/model/nepali_gpt_epoch_3.pt"   # change if needed

ckpt = torch.load(CHECKPOINT_PATH, map_location=DEVICE)
model.load_state_dict(ckpt["model_state_dict"])
model.to(DEVICE)
model.eval()

print("Loaded checkpoint from epoch:", ckpt["epoch"])
print("Val loss:", ckpt["val_loss"])


def predict_next_tokens(text, model, sp, max_len=48, top_k=5):
    model.eval()

    ids = sp.encode(text, out_type=int)
    ids = [sp.bos_id()] + ids
    ids = ids[-(max_len - 1):]   # keep recent context only

    x = torch.tensor([ids], dtype=torch.long, device=DEVICE)

    with torch.no_grad():
        logits = model(x)                     # [1, T, V]
        next_logits = logits[0, -1]          # [V]
        probs = F.softmax(next_logits, dim=-1)
        top_probs, top_ids = torch.topk(probs, k=top_k)

    results = []
    for prob, idx in zip(top_probs.tolist(), top_ids.tolist()):
        piece = sp.id_to_piece(idx)
        decoded = sp.decode([idx]) if idx not in [sp.bos_id(), sp.eos_id(), sp.pad_id(), sp.unk_id()] else piece
        results.append({
            "id": idx,
            "piece": piece,
            "decoded": decoded,
            "prob": prob
        })

    return results


# quick test
contexts = [
    "नेपाल एक",
    "काठमाडौं नेपालको",
    "म आज विद्यालय",
    "उसले मलाई",
]

for ctx in contexts:
    preds = predict_next_tokens(ctx, model, sp, max_len=MAX_LEN, top_k=5)
    print(f"\nContext: {ctx}")
    for i, p in enumerate(preds, 1):
        print(f"{i}. piece={p['piece']!r} decoded={p['decoded']!r} prob={p['prob']:.4f}")

from google.colab import drive
drive.mount('/content/drive')

